name: "Build Android App"
author: "SparkFabrik"
branding:
  icon: "smartphone"
  color: "green"
description: "Build Android (gradle), export .apk or .aab, optional upload to Play Store, optional upload to BrowserStack App Live."

inputs:
  build-type:
    description: "You can build an unsigned APK (assemble) or a signed AAB (bundle)."
    required: false
    default: "assemble"
  gradle-task:
    description: "Name of the gradle task to exec (eg. assembleDebug, assembleRelease, bundleRelease)"
    required: false
    default: "assembleDebug"
  increment-build-number:
    description: "Increment build number"
    required: false
    default: false
  package-name:
    description: "Package name"
    required: false
  keystore-content:
    description: "Keystore file content as base64 encoded string"
    required: false
  keystore-password:
    description: "Keystore password"
    required: false
  keystore-alias:
    description: "Keystore alias"
    required: false
  json-key-data:
    description: "JSON keystore file content"
    required: false
  upload-to-play-store:
    description: "Upload to Play Store"
    required: false
    default: false
  project-path:
    description: "Project path"
    required: true
  output-path:
    description: "Output path of the build"
    required: false
    default: "output.apk"
  browserstack-upload:
    description: "Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build."
    required: false
    default: false
  browserstack-username:
    description: "Browserstack username (required if browserstack-upload == true)"
    required: false
    default: ""
  browserstack-access-key:
    description: "Browserstack access key (required if browserstack-upload == true)"
    required: false
    default: ""
  fastlane-env:
    description: "Name of the env file name to pass to fastlane --env"
    required: false
  ruby-version:
    description: "Specify the ruby version you wish to use"
    default: ""
  bundler-version:
    description: "Specify the bundler version you wish to use"
    required: false
runs:
  using: "composite"
  steps:
    - id: "SETUP_RUBY"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
    - id: "SETUP_NODE"
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - id: "RUN_INDEX"
      run: node ./dist/index.js
